import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import '@copilotkit/vue/styles.css'
import './style.css'
import './layout-shell.css'
import './sidebar-hierarchy.css'
import './app-navigation-pages.css'
import './opencode-management.css'
import './skill-delete.css'
import './high-contrast-text.css'
import './copilot-markdown-contrast.css'
import './uiux-soft-technical-dark.css'
import './composer-model-placement.css'
import './conversation-stream-contrast.css'
import App from './App.vue'

createApp(App).use(ElementPlus).mount('#app')
